#======================#
#=== WORKSPACE INFO ===#

[workspace]
  resolver = "2"
  members  = ["crate", "examples/*"]
  exclude  = [".github", ".vscode", "docs/*", "promo/*", ".gitattributes", ".gitignore"]

[workspace.package]
  authors    = ["IDEDARY"]
  version    = "0.4.2"
  edition    = "2024"
  license    = "MIT OR Apache-2.0"
  repository = "https://github.com/bytestring-net/bevy-lunex"
  keywords   = ["ui", "layout", "bevy", "lunex", "bevy-lunex"]
  categories = ["gui", "mathematics", "game-development"]

#========================#
#=== PROFILE SETTINGS ===#

[profile.dev]
  debug = 0
  strip = "debuginfo"
  opt-level = 1

[profile.dev.package."*"]
  opt-level = 3

[profile.release]
  opt-level = 3
  panic = 'abort'
  debug = 0
  strip = true
  lto = "thin"
  codegen-units = 1

#===============================#
#=== DEPENDENCIES & FEATURES ===#

[workspace.dependencies]

  # LIBRARY CRATES
  bevy_lunex = { path = "crate" }

  #===========================#
  #=== GAME ENGINE SOURCE === #

  ## GAME ENGINE
  bevy = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_asset = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_app = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_color = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_ecs = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_math = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_text = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_sprite = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_image = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_render = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false}
  bevy_platform = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_reflect = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_transform = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_log = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_gizmos = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false, features = ["bevy_render"] }
  bevy_window = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_picking = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_input = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_time = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_pbr = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }
  bevy_winit = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false, features = ["custom_cursor"]}
  bevy_derive = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rs.git", branch = "ku-0.1.0", default-features = false }

  #===============================#
  #=== GAME ENGINE EXTENSIONS === #

  bevy_rich_text3d  = { git = "ssh://git@github.com/kharmic-universe-deps/bevy-rich-text3d-rs.git", branch = "ku-0.1.0", features = ["2d","3d","reflect"] }

  #===========================#
  #=== RUST MISCELLANEOUS === #
  
  radsort   = { version = "^0.1.1" }
  colored   = { version = "^3.0.0" }
  rand      = { version = "^0.9" }
  getrandom = { version = "^0.3", features = ["wasm_js"]}
